print("hello")
name = input("what is your name?")
print(f"hello {name}")
colour = input("fav colour?")
print("yes", colour, "is my fav colour too")
print("so, {name}...")
mood = input("how is it going?")